version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SenhaForte123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - mynetwork

  animeapi:
    build:
      context: ./AnimeApi/AnimeApi
      dockerfile: Dockerfile
    container_name: animeapi
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=AnimeDb;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./ProjetoReactVite/Front-CatalogoAnime
      dockerfile: Dockerfile
    container_name: front-catalogo-anime
    depends_on:
      - animeapi
    environment:
      - VITE_API_URL=http://animeapi:8080/api
    ports:
      - "3000:80"
    networks:
      - mynetwork

volumes:
  sql_data:

networks:
  mynetwork:
    driver: bridge
