version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SenhaForte123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    volumes:
      - sql_data:/var/opt/mssql

  animeapi:
    build:
      context: .
      dockerfile: AnimeApi/Dockerfile
    container_name: animeapi
    ports:
      - "5000:8080"   # mapeia porta 8080 do container para 5000 do host
    depends_on:
      - db
    environment:
      DOTNET_ENVIRONMENT: Development   # habilita Swagger
      ConnectionStrings__DefaultConnection: "Server=db;Database=AnimeDb;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  sql_data:
